language: cpp

matrix:
  include: 
    - os: linux
      addons:
        apt:
          sources:
            -ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install: true

script:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y install mysql-community-server mysql-server
  - mysql -u root -p12345678 -e "GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' IDENTIFIED BY '12345678';"
  - sudo apt-get -y install libqt5sql5-mysql
  - mkdir build && cd build
  - cmake ../
  - make
  - ldd libqt-dbhelper.so
  - cd ../
  - rm -rf build
  - echo "--------------------------------------------------------------------"
  - mkdir build && cd build
  - cmake ../tests
  - make VERBOSE=1
  - ./qt-dbhelper-tests
  - cd ../
  - rm -rf build
