language: cpp

matrix:
  include: 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - aptitude
            #- qt5-default
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo ""
  - sudo apt-get install -y dpkg
  - echo ""
  - export DEBIAN_FRONTEND=noninteractive
  - wget https://dev.mysql.com/get/mysql-apt-config_0.8.9-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.9-1_all.deb
  - cat /etc/apt/sources.list.d/mysql.list
  - sudo apt-get update
  #- sudo apt install mysql-client-core
  - sudo debconf-set-selections <<< 'mysql-community-server mysql-community-server/root-pass password 12345678'
  - sudo debconf-set-selections <<< 'mysql-community-server mysql-community-server/re-root-pass password 12345678'
  - sudo apt-get -y --allow-unauthenticated install mysql-community-server
  - mysql --version
  - mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('12345678') WHERE User='root';" 
  - mysql -u root -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" 
  - mysql -u root -e "DELETE FROM mysql.user WHERE User='';" 
  - mysql -u root -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%';" 
  - mysql -u root -e "FLUSH PRIVILEGES;"
  #- mysql -u root -p'12345678' -e "GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' IDENTIFIED BY '12345678';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' IDENTIFIED BY '12345678';"
  - sudo apt-get -y install libqt5sql5-mysql
  - echo ""
  - sudo add-apt-repository ppa:beineri/ubuntu/opt-qt595-trusty
  - sudo apt update
  - sudo apt install qt59-meta-full
  - echo ""

install: true

script:  
  - mkdir build && cd build
  - cmake ../
  - make
  - ldd libqt-dbhelper.so
  - cd ../
  - rm -rf build
  - echo "--------------------------------------------------------------------"
  - mkdir build && cd build
  - cmake ../tests
  - make VERBOSE=1
  - ./qt-dbhelper-tests
  - cd ../
  - rm -rf build
